[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
late_staking = "5eEvigM8bxcM8NgXX7aFLaHiy8XZpUKdCyQhRLNAoRWN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_jest =  "yarn jest"
